# Generated by Django 2.1.5 on 2019-02-17 20:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('season', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('episode', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('F', 'Film'), ('S', 'Series')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('season', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('finished', models.BooleanField(default=False)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ManyToManyField(through='pictures.Status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Picture'),
        ),
    ]
